### PR TITLE
System environment isolation support

### PR DESCRIPTION
**Pull request by oxsean**
Access application-specific environment variables by reading the BizClassLoader's bizModel.bizName as the key prefix:
Example:
```java
    @Before
    public void before() {
        Thread thread = Thread.currentThread();
        baseClassLoader = thread.getContextClassLoader();
        Map<String, String> env = new HashMap<>();
        env.put("key1", "value1");
        env.put("app1_key1", "value2");
        IsolatedEnvironment.takeover(TestClassLoader.class.getName(), env);
    }

    @Test
    public void takeover() {
        Assert.assertEquals("value1", System.getenv("key1"));
        Thread.currentThread().setContextClassLoader(new TestClassLoader());
        Assert.assertEquals("value2", System.getenv("key1"));
    }

    private static class TestClassLoader extends URLClassLoader {
        public TestClassLoader() {
            super(new URL[0]);
        }

        public BizModel getBizModel() {
            return new BizModel();
        }
    }

    private static class BizModel {

        public String getBizName() {
            return "app1";
        }
    }
```

## Summary by CodeRabbit

- **New Features**
	- Introduced the `IsolatedEnvironment` class for managing environment configurations across multiple business modules, enhancing modularity and preventing conflicts.
	- Added the `UnsafeUtils` class for low-level operations with static fields, facilitating performance optimization.

- **Tests**
	- Added unit tests for the `IsolatedEnvironment` class to validate its functionality in managing environment variables and context class loaders.

### CODE REVIEW

**Comment by lvjing2** [comment]
普通模块里需要怎么使用呢？怎么初始化呢？

**Comment by oxsean** [comment]
> 普通模块里需要怎么使用呢？怎么初始化呢？
和System.properties一样，在基座应用里面执行下IsolatedEnvironment.takeover()
在配置环境变量的时候，用模块的名称做为前缀即可，可以看下上面的例子

**Comment by TomorJM** [comment]
LGTM, 基础能力没问题
本月我这边有场景使用, 有问题或者优化点再单独提issue解决

**Review by TomorJM — APPROVED** [review]
LGTM

**Comment by oxsean** [comment]
OK. 我抽空看下单测失败

**Comment by lvjing2** [comment]
also fix https://github.com/sofastack/sofa-ark/issues/950

**Comment by oxsean** [comment]
@lvjing2 Unit test failed on linux fixed.

**Comment by oxsean** [comment]
It looks like the failed unit test has no relation to this PR

**Review by lvjing2 — APPROVED** [review]
LGTM

**Pull request merged**
